// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package sqlc

import (
	"context"

	"uuid"
)

const addChannelMember = `-- name: AddChannelMember :exec
INSERT INTO channel_members (channel_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddChannelMemberParams struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) AddChannelMember(ctx context.Context, arg AddChannelMemberParams) error {
	_, err := q.db.Exec(ctx, addChannelMember, arg.ChannelID, arg.UserID)
	return err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (id, workspace_id, name)
VALUES ($1, $2, $3)
RETURNING id, workspace_id, name, created_at
`

type CreateChannelParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel, arg.ID, arg.WorkspaceID, arg.Name)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels
WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const listWorkspaceChannels = `-- name: ListWorkspaceChannels :many
SELECT id, workspace_id, name, created_at
FROM channels
WHERE workspace_id = $1
ORDER BY name
`

func (q *Queries) ListWorkspaceChannels(ctx context.Context, workspaceID uuid.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listWorkspaceChannels, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectChannel = `-- name: SelectChannel :one
SELECT id, workspace_id, name, created_at
FROM channels
WHERE id = $1
`

func (q *Queries) SelectChannel(ctx context.Context, id uuid.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, selectChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
