// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_messages.sql

package sqlc

import (
	"context"

	"uuid"
)

const createChannelMessage = `-- name: CreateChannelMessage :one
INSERT INTO channel_messages (id, author_id, channel_id, thread_root_id, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, author_id, channel_id, thread_root_id, body, created_at, updated_at
`

type CreateChannelMessageParams struct {
	ID           uuid.UUID
	AuthorID     uuid.UUID
	ChannelID    uuid.UUID
	ThreadRootID *uuid.UUID
	Body         string
}

func (q *Queries) CreateChannelMessage(ctx context.Context, arg CreateChannelMessageParams) (ChannelMessage, error) {
	row := q.db.QueryRow(ctx, createChannelMessage,
		arg.ID,
		arg.AuthorID,
		arg.ChannelID,
		arg.ThreadRootID,
		arg.Body,
	)
	var i ChannelMessage
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ChannelID,
		&i.ThreadRootID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannelMessage = `-- name: DeleteChannelMessage :execrows
DELETE FROM channel_messages
WHERE id = $1
`

func (q *Queries) DeleteChannelMessage(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelMessage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listChannelMessages = `-- name: ListChannelMessages :many
SELECT id, author_id, channel_id, thread_root_id, body, created_at, updated_at
FROM channel_messages
WHERE channel_id = $1
  AND thread_root_id IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListChannelMessagesParams struct {
	ChannelID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListChannelMessages(ctx context.Context, arg ListChannelMessagesParams) ([]ChannelMessage, error) {
	rows, err := q.db.Query(ctx, listChannelMessages, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelMessage
	for rows.Next() {
		var i ChannelMessage
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.ChannelID,
			&i.ThreadRootID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelThreadMessages = `-- name: ListChannelThreadMessages :many
SELECT id, author_id, channel_id, thread_root_id, body, created_at, updated_at
FROM channel_messages
WHERE thread_root_id = $1
ORDER BY created_at
`

func (q *Queries) ListChannelThreadMessages(ctx context.Context, threadRootID *uuid.UUID) ([]ChannelMessage, error) {
	rows, err := q.db.Query(ctx, listChannelThreadMessages, threadRootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelMessage
	for rows.Next() {
		var i ChannelMessage
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.ChannelID,
			&i.ThreadRootID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectChannelMessage = `-- name: SelectChannelMessage :one
SELECT id, author_id, channel_id, thread_root_id, body, created_at, updated_at
FROM channel_messages
WHERE id = $1
`

func (q *Queries) SelectChannelMessage(ctx context.Context, id uuid.UUID) (ChannelMessage, error) {
	row := q.db.QueryRow(ctx, selectChannelMessage, id)
	var i ChannelMessage
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ChannelID,
		&i.ThreadRootID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChannelMessageBody = `-- name: UpdateChannelMessageBody :one
UPDATE channel_messages
SET body = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, author_id, channel_id, thread_root_id, body, created_at, updated_at
`

type UpdateChannelMessageBodyParams struct {
	ID   uuid.UUID
	Body string
}

func (q *Queries) UpdateChannelMessageBody(ctx context.Context, arg UpdateChannelMessageBodyParams) (ChannelMessage, error) {
	row := q.db.QueryRow(ctx, updateChannelMessageBody, arg.ID, arg.Body)
	var i ChannelMessage
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ChannelID,
		&i.ThreadRootID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
