// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: direct_messages.sql

package sqlc

import (
	"context"

	"uuid"
)

const createDirectMessage = `-- name: CreateDirectMessage :one
INSERT INTO direct_messages (id, author_id, recipient_id, body)
VALUES ($1, $2, $3, $4)
RETURNING id, author_id, recipient_id, body, created_at, updated_at
`

type CreateDirectMessageParams struct {
	ID          uuid.UUID
	AuthorID    uuid.UUID
	RecipientID uuid.UUID
	Body        string
}

func (q *Queries) CreateDirectMessage(ctx context.Context, arg CreateDirectMessageParams) (DirectMessage, error) {
	row := q.db.QueryRow(ctx, createDirectMessage,
		arg.ID,
		arg.AuthorID,
		arg.RecipientID,
		arg.Body,
	)
	var i DirectMessage
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.RecipientID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDirectMessage = `-- name: DeleteDirectMessage :execrows
DELETE FROM direct_messages
WHERE id = $1
`

func (q *Queries) DeleteDirectMessage(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDirectMessage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDirectMessages = `-- name: ListDirectMessages :many
SELECT id, author_id, recipient_id, body, created_at, updated_at
FROM direct_messages
WHERE LEAST(author_id, recipient_id) = LEAST($1, $2)
  AND GREATEST(author_id, recipient_id) = GREATEST($1, $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListDirectMessagesParams struct {
	AuthorID   uuid.UUID
	AuthorID_2 uuid.UUID
	Limit      int32
	Offset     int32
}

func (q *Queries) ListDirectMessages(ctx context.Context, arg ListDirectMessagesParams) ([]DirectMessage, error) {
	rows, err := q.db.Query(ctx, listDirectMessages,
		arg.AuthorID,
		arg.AuthorID_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DirectMessage
	for rows.Next() {
		var i DirectMessage
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.RecipientID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectDirectMessage = `-- name: SelectDirectMessage :one
SELECT id, author_id, recipient_id, body, created_at, updated_at
FROM direct_messages
WHERE id = $1
`

func (q *Queries) SelectDirectMessage(ctx context.Context, id uuid.UUID) (DirectMessage, error) {
	row := q.db.QueryRow(ctx, selectDirectMessage, id)
	var i DirectMessage
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.RecipientID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDirectMessageBody = `-- name: UpdateDirectMessageBody :one
UPDATE direct_messages
SET body = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, author_id, recipient_id, body, created_at, updated_at
`

type UpdateDirectMessageBodyParams struct {
	ID   uuid.UUID
	Body string
}

func (q *Queries) UpdateDirectMessageBody(ctx context.Context, arg UpdateDirectMessageBodyParams) (DirectMessage, error) {
	row := q.db.QueryRow(ctx, updateDirectMessageBody, arg.ID, arg.Body)
	var i DirectMessage
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.RecipientID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
