// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package sqlc

import (
	"context"

	"uuid"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, author_id, channel_id, thread_root_id, body)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, author_id, channel_id, thread_root_id, body, created_at, updated_at
`

type CreateMessageParams struct {
	ID           uuid.UUID
	AuthorID     uuid.UUID
	ChannelID    uuid.UUID
	ThreadRootID *uuid.UUID
	Body         string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.AuthorID,
		arg.ChannelID,
		arg.ThreadRootID,
		arg.Body,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ChannelID,
		&i.ThreadRootID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMessage = `-- name: DeleteMessage :exec
DELETE FROM messages
WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const listChannelMessages = `-- name: ListChannelMessages :many
SELECT id, author_id, channel_id, thread_root_id, body, created_at, updated_at
FROM messages
WHERE channel_id = $1
  AND thread_root_id IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListChannelMessagesParams struct {
	ChannelID uuid.UUID
	Limit     int32
	Offset    int32
}

func (q *Queries) ListChannelMessages(ctx context.Context, arg ListChannelMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listChannelMessages, arg.ChannelID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.ChannelID,
			&i.ThreadRootID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadMessages = `-- name: ListThreadMessages :many
SELECT id, author_id, channel_id, thread_root_id, body, created_at, updated_at
FROM messages
WHERE thread_root_id = $1
ORDER BY created_at
`

func (q *Queries) ListThreadMessages(ctx context.Context, threadRootID *uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listThreadMessages, threadRootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.ChannelID,
			&i.ThreadRootID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectMessage = `-- name: SelectMessage :one
SELECT id, author_id, channel_id, thread_root_id, body, created_at, updated_at
FROM messages
WHERE id = $1
`

func (q *Queries) SelectMessage(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, selectMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ChannelID,
		&i.ThreadRootID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMessageBody = `-- name: UpdateMessageBody :one
UPDATE messages
SET body = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, author_id, channel_id, thread_root_id, body, created_at, updated_at
`

type UpdateMessageBodyParams struct {
	ID   uuid.UUID
	Body string
}

func (q *Queries) UpdateMessageBody(ctx context.Context, arg UpdateMessageBodyParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessageBody, arg.ID, arg.Body)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.ChannelID,
		&i.ThreadRootID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
