// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

type Channel struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	CreatedAt   pgtype.Timestamptz
}

type ChannelMember struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
	JoinedAt  pgtype.Timestamptz
}

type ChannelMessage struct {
	ID           uuid.UUID
	AuthorID     uuid.UUID
	ChannelID    uuid.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Body         string
	ThreadRootID *uuid.UUID
	ReplyCount   int64
}

type DirectMessage struct {
	ID          uuid.UUID
	AuthorID    uuid.UUID
	RecipientID uuid.UUID
	Body        string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID          uuid.UUID
	Email       string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}

type UserIdentity struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	AuthSubject string
	AuthIssuer  string
	CreatedAt   pgtype.Timestamptz
}

type Workspace struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type WorkspaceMember struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
	JoinedAt    pgtype.Timestamptz
}
