// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

type Channel struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	CreatedAt   pgtype.Timestamptz
}

type ChannelMember struct {
	ChannelID uuid.UUID
	UserID    uuid.UUID
	JoinedAt  pgtype.Timestamptz
}

type Message struct {
	ID           uuid.UUID
	AuthorID     uuid.UUID
	ChannelID    uuid.UUID
	ThreadRootID *uuid.UUID
	Body         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID          uuid.UUID
	Email       string
	DisplayName string
	CreatedAt   pgtype.Timestamptz
}

type Workspace struct {
	ID        uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
}

type WorkspaceMember struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
	JoinedAt    pgtype.Timestamptz
}
