// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"uuid"
)

type Querier interface {
	AddChannelMember(ctx context.Context, arg AddChannelMemberParams) error
	AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) error
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteChannel(ctx context.Context, id uuid.UUID) error
	DeleteMessage(ctx context.Context, id uuid.UUID) error
	DeleteWorkspace(ctx context.Context, id uuid.UUID) error
	ListChannelMessages(ctx context.Context, arg ListChannelMessagesParams) ([]Message, error)
	ListThreadMessages(ctx context.Context, threadRootID *uuid.UUID) ([]Message, error)
	ListUserWorkspaces(ctx context.Context, userID uuid.UUID) ([]Workspace, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListWorkspaceChannels(ctx context.Context, workspaceID uuid.UUID) ([]Channel, error)
	SelectChannel(ctx context.Context, id uuid.UUID) (Channel, error)
	SelectMessage(ctx context.Context, id uuid.UUID) (Message, error)
	SelectUser(ctx context.Context, id uuid.UUID) (User, error)
	SelectWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error)
	UpdateMessageBody(ctx context.Context, arg UpdateMessageBodyParams) (Message, error)
}

var _ Querier = (*Queries)(nil)
