// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_identities.sql

package sqlc

import (
	"context"

	"uuid"
)

const createUserIdentity = `-- name: CreateUserIdentity :one
INSERT INTO user_identities (id, user_id, auth_subject, auth_issuer)
VALUES ($1, $2, $3, $4)
ON CONFLICT (auth_issuer, auth_subject) DO NOTHING
RETURNING id, user_id, auth_subject, auth_issuer, created_at
`

type CreateUserIdentityParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	AuthSubject string
	AuthIssuer  string
}

func (q *Queries) CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, createUserIdentity,
		arg.ID,
		arg.UserID,
		arg.AuthSubject,
		arg.AuthIssuer,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthSubject,
		&i.AuthIssuer,
		&i.CreatedAt,
	)
	return i, err
}

const listUserIdentities = `-- name: ListUserIdentities :many
SELECT id, user_id, auth_subject, auth_issuer, created_at
FROM user_identities
`

func (q *Queries) ListUserIdentities(ctx context.Context) ([]UserIdentity, error) {
	rows, err := q.db.Query(ctx, listUserIdentities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserIdentity
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AuthSubject,
			&i.AuthIssuer,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserIdentity = `-- name: SelectUserIdentity :one
SELECT id, user_id, auth_subject, auth_issuer, created_at
FROM user_identities
WHERE id = $1
`

func (q *Queries) SelectUserIdentity(ctx context.Context, id uuid.UUID) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, selectUserIdentity, id)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthSubject,
		&i.AuthIssuer,
		&i.CreatedAt,
	)
	return i, err
}

const selectUserIdentityByUserID = `-- name: SelectUserIdentityByUserID :one
SELECT id, user_id, auth_subject, auth_issuer, created_at
FROM user_identities
WHERE user_id = $1
`

func (q *Queries) SelectUserIdentityByUserID(ctx context.Context, userID uuid.UUID) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, selectUserIdentityByUserID, userID)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AuthSubject,
		&i.AuthIssuer,
		&i.CreatedAt,
	)
	return i, err
}
